# Generated by Django 2.2 on 2020-12-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='DATE_OF_REGISTRATION',
            field=models.DateField(null=True),
        ),
    ]
