# Generated by Django 2.2 on 2020-12-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_master', '0002_auto_20201223_0215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyData',
        ),
    ]
