# Generated by Django 2.2 on 2020-12-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_master', '0004_companydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyData',
        ),
    ]
